openapi: 3.0.0
info:
  title: Market Interaction Core API
  version: 1.0.0
  description: Core API for market interactions
paths:
  /core:
    get:
      summary: Get core data
      responses:
        '200':
          description: Success
