openapi: 3.0.0
info:
  title: Market Interaction Events API
  version: 1.0.0
  description: API for market interaction events
servers:
  - url: https://api.example.com/v1
tags:
  - name: events
    description: Event operations
paths:
  /events:
    get:
      summary: Get events
      description: Retrieve a list of market interaction events
      operationId: getEvents
      tags:
        - events
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventsResponse'
              example:
                events: []
components:
  schemas:
    EventsResponse:
      type: object
      properties:
        events:
          type: array
          items:
            type: object
